apiVersion: v1
kind: ServiceAccount
metadata:
  name: natureprotector-deploy-verifier
  labels:
    app.kubernetes.io/name: natureprotector-deploy-verifier
    app.kubernetes.io/part-of: natureprotector
automountServiceAccountToken: true
