apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: natureprotector-prevention
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: natureprotector-prevention
