apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: natureprotector-app
spec:
  tags: []
  rabbitmqClusterReference:
    connectionSecret: {name: natureprotector-rabbitmq-default-user}
  importCredentialsSecret: {name: np-rabbitmq-app-credentials}
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: natureprotector-app
spec:
  vhost: "/"
  user: "np_app"
  permissions:
    configure: '^np\.'
    write: '^np\.'
    read: '^np\.'
  rabbitmqClusterReference:
    connectionSecret: {name: natureprotector-rabbitmq-default-user}
---
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: natureprotector-primary-work-queue-policy
spec:
  name: natureprotector-primary-work-queue
  pattern: '^np\.ingestion\.readings$'
  applyTo: queues
  definition:
    overflow: reject-publish
    max-length-bytes: 1073741824
    delivery-limit: 8
  priority: 20
  rabbitmqClusterReference:
    connectionSecret: {name: natureprotector-rabbitmq-default-user}
