apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: natureprotector-rabbitmq
  labels:
    app.kubernetes.io/name: natureprotector-rabbitmq
    app.kubernetes.io/part-of: natureprotector
spec:
  replicas: 3
  image: RABBITMQ_IMAGE_BY_DIGEST
  persistence:
    storageClassName: premium-rwo
    storage: 50Gi
  resources:
    requests: {cpu: "1", memory: 4Gi}
    limits: {cpu: "2", memory: 4Gi}
  service:
    type: LoadBalancer
    annotations:
      networking.gke.io/load-balancer-type: Internal
  tls:
    secretName: np-rabbitmq-server-tls
    caSecretName: np-rabbitmq-ca
    disableNonTLSListeners: true
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      queue_leader_locator = balanced
      default_queue_type = quorum
      quorum_queue.initial_cluster_size = 3
      disk_free_limit.absolute = 5GB
      vm_memory_high_watermark.relative = 0.6
      ssl_options.fail_if_no_peer_cert = false
      management.ssl.port = 15671
      consumer_timeout = 900000
  override:
    service:
      spec:
        externalTrafficPolicy: Local
        loadBalancerIP: 127.0.0.1 # from-param: ${rabbitmq_load_balancer_ip}
        ports:
          - {name: amqps, port: 5671, targetPort: 5671, protocol: TCP, appProtocol: amqps}
          - {name: management, port: 15672, targetPort: 15672, protocol: TCP, appProtocol: http}
          - {name: management-tls, port: 15671, targetPort: 15671, protocol: TCP, appProtocol: https}
          - {name: prometheus-tls, port: 15691, targetPort: 15691, protocol: TCP, appProtocol: prometheus.io/metric-tls}
    statefulSet:
      spec:
        template:
          metadata:
            labels:
              np.network/rabbitmq: "true"
          spec:
            containers:
              - name: rabbitmq
                env:
                  - name: K8S_HOSTNAME_SUFFIX
                    value: .$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local
                  - name: RABBITMQ_NODENAME
                    value: rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local
            terminationGracePeriodSeconds: 120
            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: topology.kubernetes.io/zone
                whenUnsatisfiable: DoNotSchedule
                labelSelector:
                  matchLabels:
                    np.network/rabbitmq: "true"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: natureprotector-rabbitmq
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: natureprotector-rabbitmq
