apiVersion: v1
kind: ServiceAccount
metadata:
  name: natureprotector-secret-sync
  annotations:
    iam.gke.io/gcp-service-account: missing-secret-sync-gsa # from-param: ${secret_sync_gsa}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: natureprotector-runtime
spec:
  provider: gke
  parameters:
    secrets: "MISSING_RUNTIME_SECRET_RESOURCES" # from-param: ${runtime_secret_resources}
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: np-runtime-secrets
spec:
  serviceAccountName: natureprotector-secret-sync
  secretProviderClassName: natureprotector-runtime
  secretObject:
    type: Opaque
    data:
      - {sourcePath: postgres-app-password, targetKey: postgres-app-password}
      - {sourcePath: rabbitmq-username, targetKey: rabbitmq-username}
      - {sourcePath: rabbitmq-password, targetKey: rabbitmq-password}
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: np-rabbitmq-app-credentials
spec:
  serviceAccountName: natureprotector-secret-sync
  secretProviderClassName: natureprotector-runtime
  secretObject:
    type: Opaque
    data:
      - {sourcePath: rabbitmq-username, targetKey: username}
      - {sourcePath: rabbitmq-password, targetKey: password}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: natureprotector-rabbitmq-tls
spec:
  provider: gke
  parameters:
    secrets: "MISSING_RABBITMQ_TLS_SECRET_RESOURCES" # from-param: ${rabbitmq_tls_secret_resources}
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: np-rabbitmq-server-tls
spec:
  serviceAccountName: natureprotector-secret-sync
  secretProviderClassName: natureprotector-rabbitmq-tls
  secretObject:
    type: kubernetes.io/tls
    data:
      - {sourcePath: tls.crt, targetKey: tls.crt}
      - {sourcePath: tls.key, targetKey: tls.key}
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: np-rabbitmq-ca
spec:
  serviceAccountName: natureprotector-secret-sync
  secretProviderClassName: natureprotector-rabbitmq-tls
  secretObject:
    type: Opaque
    data:
      - {sourcePath: ca.crt, targetKey: ca.crt}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: natureprotector-cloud-sql-ca
spec:
  provider: gke
  parameters:
    secrets: "MISSING_CLOUD_SQL_CA_SECRET_RESOURCES" # from-param: ${cloud_sql_ca_secret_resources}
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: np-cloud-sql-ca
spec:
  serviceAccountName: natureprotector-secret-sync
  secretProviderClassName: natureprotector-cloud-sql-ca
  secretObject:
    type: Opaque
    data:
      - {sourcePath: server-ca.pem, targetKey: server-ca.pem}
