apiVersion: v1
kind: ServiceAccount
metadata:
  name: natureprotector-prevention
  annotations:
    iam.gke.io/gcp-service-account: missing-prevention-gsa # from-param: ${prevention_gsa}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: natureprotector-otel
  annotations:
    iam.gke.io/gcp-service-account: missing-otel-gsa # from-param: ${otel_gsa}
