// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatureProtector.Infrastructure.Postgres.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NatureProtector.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(NatureProtectorControlDbContext))]
    [Migration("20260407203545_AddSimulationRunsToControlSchema")]
    partial class AddSimulationRunsToControlSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.AreaContextRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<double>("CriticalInfrastructureExposure")
                        .HasColumnType("double precision");

                    b.Property<double>("PopulationExposure")
                        .HasColumnType("double precision");

                    b.Property<string>("Seasonality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("VegetationDensity")
                        .HasColumnType("double precision");

                    b.Property<string>("VegetationType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId")
                        .IsUnique();

                    b.ToTable("area_contexts", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("GeometryGeoJson")
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId", "Code")
                        .IsUnique();

                    b.ToTable("areas", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VersionNumber")
                        .IsUnique();

                    b.ToTable("configuration_versions", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.DatasetArtifactRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Checksum")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DatasetCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DatasetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetCode", "AreaCode", "Version")
                        .IsUnique();

                    b.ToTable("dataset_artifacts", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.GridCellRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AltitudeMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<double?>("AspectDegrees")
                        .HasColumnType("double precision");

                    b.Property<string>("CellCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("CentroidLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("CentroidLongitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConjuncturalHazard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DominantForestType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DominantFuelModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LandCoverClass")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PolygonGeoJson")
                        .HasColumnType("text");

                    b.Property<double?>("SlopeDegrees")
                        .HasColumnType("double precision");

                    b.Property<string>("StructuralHazard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("TreeCoverDensity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("AreaId", "CellCode")
                        .IsUnique();

                    b.ToTable("grid_cells", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.RuleSetVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("rule_set_versions", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ScenarioDatasetBindingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BindingRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DatasetArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DatasetArtifactId");

                    b.HasIndex("ScenarioId", "DatasetArtifactId", "BindingRole")
                        .IsUnique();

                    b.ToTable("scenario_dataset_bindings", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseScenarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScenarioKind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseScenarioId");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("AreaId", "Code")
                        .IsUnique();

                    b.ToTable("scenario_definitions", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorNetworkRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId", "Name")
                        .IsUnique();

                    b.ToTable("sensor_networks", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorNodeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AltitudeMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GridCellId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstallationProfile")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("NetworkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("GridCellId");

                    b.HasIndex("NetworkId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("AreaId", "GridCellId", "Name")
                        .IsUnique();

                    b.ToTable("sensor_nodes", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorProfileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccuracyProfileJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FaultProfileJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NoiseProfileJson")
                        .HasColumnType("text");

                    b.Property<string>("PublicationPolicyJson")
                        .HasColumnType("text");

                    b.Property<string>("SensorFamily")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId", "Name")
                        .IsUnique();

                    b.ToTable("sensor_profiles", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SimulationRunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExecutionSeed")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LogicalStartTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfCycles")
                        .HasColumnType("integer");

                    b.Property<string>("ScenarioCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("AreaId", "CreatedAt");

                    b.HasIndex("ScenarioId", "CreatedAt");

                    b.ToTable("simulation_runs", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.AreaContextRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithOne("Context")
                        .HasForeignKey("NatureProtector.Infrastructure.Postgres.Control.AreaContextRecord", "AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("Areas")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.GridCellRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany("GridCells")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("GridCells")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.RuleSetVersionRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("RuleSetVersions")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ScenarioDatasetBindingRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.DatasetArtifactRecord", "DatasetArtifact")
                        .WithMany("ScenarioBindings")
                        .HasForeignKey("DatasetArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", "Scenario")
                        .WithMany("DatasetBindings")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetArtifact");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany("Scenarios")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", "BaseScenario")
                        .WithMany("DerivedScenarios")
                        .HasForeignKey("BaseScenarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("Scenarios")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("BaseScenario");

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorNetworkRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("SensorNetworks")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorNodeRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany("SensorNodes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("SensorNodes")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.GridCellRecord", "GridCell")
                        .WithMany("SensorNodes")
                        .HasForeignKey("GridCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SensorNetworkRecord", "Network")
                        .WithMany("SensorNodes")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SensorProfileRecord", "Profile")
                        .WithMany("SensorNodes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("ConfigurationVersion");

                    b.Navigation("GridCell");

                    b.Navigation("Network");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorProfileRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("SensorProfiles")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SimulationRunRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany("SimulationRuns")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("SimulationRuns")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", "Scenario")
                        .WithMany("SimulationRuns")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("ConfigurationVersion");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", b =>
                {
                    b.Navigation("Context");

                    b.Navigation("GridCells");

                    b.Navigation("Scenarios");

                    b.Navigation("SensorNodes");

                    b.Navigation("SimulationRuns");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("GridCells");

                    b.Navigation("RuleSetVersions");

                    b.Navigation("Scenarios");

                    b.Navigation("SensorNetworks");

                    b.Navigation("SensorNodes");

                    b.Navigation("SensorProfiles");

                    b.Navigation("SimulationRuns");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.DatasetArtifactRecord", b =>
                {
                    b.Navigation("ScenarioBindings");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.GridCellRecord", b =>
                {
                    b.Navigation("SensorNodes");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", b =>
                {
                    b.Navigation("DatasetBindings");

                    b.Navigation("DerivedScenarios");

                    b.Navigation("SimulationRuns");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorNetworkRecord", b =>
                {
                    b.Navigation("SensorNodes");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorProfileRecord", b =>
                {
                    b.Navigation("SensorNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
