// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatureProtector.Infrastructure.Postgres.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NatureProtector.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(NatureProtectorControlDbContext))]
    partial class NatureProtectorControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.AreaContextRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<double>("CriticalInfrastructureExposure")
                        .HasColumnType("double precision");

                    b.Property<double>("PopulationExposure")
                        .HasColumnType("double precision");

                    b.Property<string>("Seasonality")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("VegetationDensity")
                        .HasColumnType("double precision");

                    b.Property<string>("VegetationType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId")
                        .IsUnique();

                    b.ToTable("area_contexts", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("GeometryGeoJson")
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId", "Code")
                        .IsUnique();

                    b.ToTable("areas", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VersionNumber")
                        .IsUnique();

                    b.ToTable("configuration_versions", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.DatasetArtifactRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Checksum")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DatasetCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DatasetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DatasetCode", "AreaCode", "Version")
                        .IsUnique();

                    b.ToTable("dataset_artifacts", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.GridCellRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AltitudeMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<double?>("AspectDegrees")
                        .HasColumnType("double precision");

                    b.Property<string>("CellCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("CentroidLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("CentroidLongitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConjuncturalHazard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DominantForestType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DominantFuelModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LandCoverClass")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PolygonGeoJson")
                        .HasColumnType("text");

                    b.Property<double?>("SlopeDegrees")
                        .HasColumnType("double precision");

                    b.Property<string>("StructuralHazard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("TreeCoverDensity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("AreaId", "CellCode")
                        .IsUnique();

                    b.ToTable("grid_cells", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.RuleSetVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("rule_set_versions", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.RuntimeOperationRecord", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("log_correlation");

                    b.Property<DateTimeOffset>("DeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_at");

                    b.Property<string>("EvidenceId")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("evidence_id");

                    b.Property<string>("EvidenceLocation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("evidence_location");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("failure_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("boolean")
                        .HasColumnName("is_operational");

                    b.Property<Guid?>("LaunchLeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("launch_lease_token");

                    b.Property<DateTimeOffset?>("LaunchLeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("launch_lease_until");

                    b.Property<string>("ProcessingState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("processing_state");

                    b.Property<DateTimeOffset?>("ProducerCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("producer_completed_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderExecutionName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("provider_execution_name");

                    b.Property<string>("ProviderOperationName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("provider_operation_name");

                    b.Property<string>("ProviderState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_state");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("RequestedState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("requested_state");

                    b.Property<string>("RunState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("run_state");

                    b.Property<Guid?>("SimulationRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_run_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("SystemCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("system_completed_at");

                    b.Property<string>("TerminalOutcome")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("terminal_outcome");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OperationId");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("IsOperational")
                        .IsUnique()
                        .HasFilter("is_operational = TRUE AND terminal_outcome IS NULL");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("SimulationRunId")
                        .IsUnique();

                    b.ToTable("runtime_orchestrator_executions", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ScenarioDatasetBindingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BindingRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DatasetArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DatasetArtifactId");

                    b.HasIndex("ScenarioId", "DatasetArtifactId", "BindingRole")
                        .IsUnique();

                    b.ToTable("scenario_dataset_bindings", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseScenarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScenarioKind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseScenarioId");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("AreaId", "Code")
                        .IsUnique();

                    b.ToTable("scenario_definitions", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorNetworkRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId", "Name")
                        .IsUnique();

                    b.ToTable("sensor_networks", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorNodeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AltitudeMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GridCellId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstallationProfile")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("NetworkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("GridCellId");

                    b.HasIndex("NetworkId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("AreaId", "GridCellId", "Name")
                        .IsUnique();

                    b.ToTable("sensor_nodes", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorProfileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccuracyProfileJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FaultProfileJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NoiseProfileJson")
                        .HasColumnType("text");

                    b.Property<string>("PublicationPolicyJson")
                        .HasColumnType("text");

                    b.Property<string>("SensorFamily")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId", "Name")
                        .IsUnique();

                    b.ToTable("sensor_profiles", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SimulationRunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExecutionSeed")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LogicalStartTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfCycles")
                        .HasColumnType("integer");

                    b.Property<string>("OrchestratorCorrelationId")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("orchestrator_correlation_id");

                    b.Property<string>("ScenarioCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("OrchestratorCorrelationId")
                        .IsUnique();

                    b.HasIndex("AreaId", "CreatedAt");

                    b.HasIndex("ScenarioId", "CreatedAt");

                    b.ToTable("simulation_runs", "control");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Pipeline.InboxEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("IngestTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LastProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptNotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("QuarantinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("SimulationRunId", "Status");

                    b.HasIndex("Status", "NextAttemptNotBefore");

                    b.HasIndex("Status", "ReceivedAt");

                    b.ToTable("event_inbox", "pipeline");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Pipeline.ProcessingAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InboxEventId")
                        .HasColumnType("uuid");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InboxEventId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("processing_attempts", "pipeline");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Pipeline.QuarantinedEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("FinalAttemptNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("InboxEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("QuarantineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("QuarantineReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("QuarantinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("InboxEventId");

                    b.HasIndex("QuarantinedAt");

                    b.ToTable("quarantined_events", "pipeline");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Pipeline.RejectedEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("RawBodyUtf8")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("InboxEventId");

                    b.HasIndex("RejectedAt");

                    b.ToTable("rejected_events", "pipeline");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.AcceptedReadingLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("IngestTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OperationalState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("AreaId", "EventTime");

                    b.HasIndex("SensorId", "EventTime");

                    b.ToTable("accepted_reading_log", "projection");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.AlertStateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlertCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaOperationalStateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AreaOperationalStateId");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("AreaId", "AlertCode", "Status");

                    b.ToTable("alert_state", "projection");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.AreaCycleSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateRiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("AggregateRiskScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("AlertEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlertOutcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<int>("BlockedCount")
                        .HasColumnType("integer");

                    b.Property<int>("CellCount")
                        .HasColumnType("integer");

                    b.Property<int>("CycleIndex")
                        .HasColumnType("integer");

                    b.Property<int>("EligibleCount")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("boolean");

                    b.Property<int>("MissingCount")
                        .HasColumnType("integer");

                    b.Property<int>("ObservedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SnapshotTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "CycleIndex");

                    b.HasIndex("SimulationRunId", "CycleIndex", "AreaId")
                        .IsUnique();

                    b.ToTable("area_cycle_snapshot", "projection");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.AreaOperationalStateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateRiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("AggregateRiskScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("AlertCooldownUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<int>("AssessmentCount")
                        .HasColumnType("integer");

                    b.Property<string>("CarryForwardStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Current");

                    b.Property<Guid>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Complete");

                    b.Property<int?>("CycleIndex")
                        .HasColumnType("integer");

                    b.Property<string>("FreshnessStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Fresh");

                    b.Property<int>("PendingAlertCycles")
                        .HasColumnType("integer");

                    b.Property<string>("PendingAlertState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("None");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SnapshotTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AreaId")
                        .IsUnique();

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("SimulationRunId");

                    b.HasIndex("SnapshotTimestamp");

                    b.ToTable("area_operational_state", "projection");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.AreaRiskSnapshotLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateRiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("AggregateRiskScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<int>("AssessmentCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SnapshotTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId");

                    b.HasIndex("AreaId", "SnapshotTimestamp");

                    b.ToTable("area_risk_snapshot_log", "projection");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.CellCycleSnapshotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateRiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("AggregateRiskScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<int>("BlockedCount")
                        .HasColumnType("integer");

                    b.Property<int>("CycleIndex")
                        .HasColumnType("integer");

                    b.Property<int>("EligibleCount")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("GridCellId")
                        .HasColumnType("uuid");

                    b.Property<int>("MissingCount")
                        .HasColumnType("integer");

                    b.Property<int>("ObservedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SnapshotTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId", "CycleIndex", "GridCellId")
                        .IsUnique();

                    b.ToTable("cell_cycle_snapshot", "projection");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.CellOperationalStateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CarryForwardStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Current");

                    b.Property<string>("CoverageStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Complete");

                    b.Property<string>("FreshnessStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Fresh");

                    b.Property<Guid>("GridCellId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LatestAssessmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("SensorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("SnapshotTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GridCellId")
                        .IsUnique();

                    b.HasIndex("SensorId");

                    b.HasIndex("AreaId", "SnapshotTimestamp");

                    b.ToTable("cell_operational_state", "projection");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.CycleObservationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GridCellId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricOrigin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("SimulationRunId", "CycleIndex", "SensorId")
                        .IsUnique();

                    b.ToTable("cycle_observation", "projection");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.CycleSettlementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlockedSensorIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleIndex")
                        .HasColumnType("integer");

                    b.Property<string>("EligibleSensorIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedSensorIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FinalizationReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("boolean");

                    b.Property<string>("MissingSensorIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservedSensorIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "Status");

                    b.HasIndex("SimulationRunId", "CycleIndex")
                        .IsUnique();

                    b.ToTable("cycle_settlement", "projection");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.DailyCellStateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AntecedentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<double?>("BuildupIndex")
                        .HasColumnType("double precision");

                    b.Property<string>("CandidateParameterSetVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ConfigurationVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DailyPrecipitationMillimeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("DroughtCode")
                        .HasColumnType("double precision");

                    b.Property<string>("DroughtContext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("DuffMoistureCode")
                        .HasColumnType("double precision");

                    b.Property<double?>("FineFuelMoistureCode")
                        .HasColumnType("double precision");

                    b.Property<string>("FireIndexProvenance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FireWeatherCalculationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Missing");

                    b.Property<double?>("FireWeatherIndex")
                        .HasColumnType("double precision");

                    b.Property<string>("FireWeatherLimitations")
                        .HasColumnType("text");

                    b.Property<Guid>("GridCellId")
                        .HasColumnType("uuid");

                    b.Property<double?>("InitialSpreadIndex")
                        .HasColumnType("double precision");

                    b.Property<string>("KbdiCalculationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Missing");

                    b.Property<string>("KbdiLimitations")
                        .HasColumnType("text");

                    b.Property<double?>("KeetchByramDroughtIndex")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("LastSourceEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("LatestHumidityPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("LatestWindSpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("LogicalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MaxTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double?>("NormalizedFireWeatherIndex")
                        .HasColumnType("double precision");

                    b.Property<double?>("NormalizedKeetchByramDroughtIndex")
                        .HasColumnType("double precision");

                    b.Property<double?>("PreviousKeetchByramDroughtIndex")
                        .HasColumnType("double precision");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SensorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationVersionId");

                    b.HasIndex("GridCellId");

                    b.HasIndex("SimulationRunId");

                    b.HasIndex("SensorId", "LogicalDate");

                    b.HasIndex("AreaId", "GridCellId", "LogicalDate", "SimulationRunId")
                        .IsUnique();

                    b.ToTable("daily_cell_state", "projection");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.RiskAssessmentLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AdjustedScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<double>("BaseRisk")
                        .HasColumnType("double precision");

                    b.Property<string>("CalculationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("CandidateFallback");

                    b.Property<double>("ConfidenceFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DominantDriver")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Mixed");

                    b.Property<double>("DroughtComponent")
                        .HasColumnType("double precision");

                    b.Property<string>("ExplanationSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<double>("FuelComponent")
                        .HasColumnType("double precision");

                    b.Property<double>("GeomorphologyComponent")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("GridCellId")
                        .HasColumnType("uuid");

                    b.Property<double>("HazardComponent")
                        .HasColumnType("double precision");

                    b.Property<double>("IntegrityFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(1.0);

                    b.Property<string>("Limitations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("MeteorologyComponent")
                        .HasColumnType("double precision");

                    b.Property<string>("ParameterSetVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Unknown");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<int>("Score100")
                        .HasColumnType("integer");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SimulationRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceEventId")
                        .HasColumnType("uuid");

                    b.Property<double>("TerritoryComponent")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.HasIndex("SimulationRunId");

                    b.HasIndex("SourceEventId")
                        .IsUnique();

                    b.HasIndex("AreaId", "Timestamp");

                    b.HasIndex("GridCellId", "Timestamp");

                    b.HasIndex("AreaId", "SimulationRunId", "Timestamp");

                    b.ToTable("risk_assessment_log", "projection");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Users.RoleRecord", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "user_base");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Sim"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Pipeline"
                        });
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Users.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "user_base");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Users.UserRoleRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId1");

                    b.ToTable("user_roles", "user_base");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.AreaContextRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithOne("Context")
                        .HasForeignKey("NatureProtector.Infrastructure.Postgres.Control.AreaContextRecord", "AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("Areas")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.GridCellRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany("GridCells")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("GridCells")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.RuleSetVersionRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("RuleSetVersions")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.RuntimeOperationRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SimulationRunRecord", "SimulationRun")
                        .WithOne("RuntimeOperation")
                        .HasForeignKey("NatureProtector.Infrastructure.Postgres.Control.RuntimeOperationRecord", "SimulationRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ScenarioDatasetBindingRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.DatasetArtifactRecord", "DatasetArtifact")
                        .WithMany("ScenarioBindings")
                        .HasForeignKey("DatasetArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", "Scenario")
                        .WithMany("DatasetBindings")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatasetArtifact");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany("Scenarios")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", "BaseScenario")
                        .WithMany("DerivedScenarios")
                        .HasForeignKey("BaseScenarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("Scenarios")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("BaseScenario");

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorNetworkRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("SensorNetworks")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorNodeRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany("SensorNodes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("SensorNodes")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.GridCellRecord", "GridCell")
                        .WithMany("SensorNodes")
                        .HasForeignKey("GridCellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SensorNetworkRecord", "Network")
                        .WithMany("SensorNodes")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SensorProfileRecord", "Profile")
                        .WithMany("SensorNodes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("ConfigurationVersion");

                    b.Navigation("GridCell");

                    b.Navigation("Network");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorProfileRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("SensorProfiles")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SimulationRunRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany("SimulationRuns")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany("SimulationRuns")
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", "Scenario")
                        .WithMany("SimulationRuns")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("ConfigurationVersion");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Pipeline.ProcessingAttemptRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Pipeline.InboxEventRecord", "InboxEvent")
                        .WithMany("Attempts")
                        .HasForeignKey("InboxEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboxEvent");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Pipeline.QuarantinedEventRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Pipeline.InboxEventRecord", "InboxEvent")
                        .WithMany("Quarantines")
                        .HasForeignKey("InboxEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboxEvent");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Pipeline.RejectedEventRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Pipeline.InboxEventRecord", "InboxEvent")
                        .WithMany("Rejections")
                        .HasForeignKey("InboxEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InboxEvent");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.AcceptedReadingLogRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SensorNodeRecord", "SensorNode")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("SensorNode");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.AlertStateRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Projection.AreaOperationalStateRecord", "AreaOperationalState")
                        .WithMany("Alerts")
                        .HasForeignKey("AreaOperationalStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany()
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("AreaOperationalState");

                    b.Navigation("ConfigurationVersion");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.AreaOperationalStateRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany()
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SimulationRunRecord", "SimulationRun")
                        .WithMany()
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");

                    b.Navigation("ConfigurationVersion");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.AreaRiskSnapshotLogRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SimulationRunRecord", "SimulationRun")
                        .WithMany()
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.CellOperationalStateRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.GridCellRecord", "GridCell")
                        .WithMany()
                        .HasForeignKey("GridCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SensorNodeRecord", "SensorNode")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");

                    b.Navigation("GridCell");

                    b.Navigation("SensorNode");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.DailyCellStateRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", "ConfigurationVersion")
                        .WithMany()
                        .HasForeignKey("ConfigurationVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.GridCellRecord", "GridCell")
                        .WithMany()
                        .HasForeignKey("GridCellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SensorNodeRecord", "SensorNode")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SimulationRunRecord", "SimulationRun")
                        .WithMany()
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");

                    b.Navigation("ConfigurationVersion");

                    b.Navigation("GridCell");

                    b.Navigation("SensorNode");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.RiskAssessmentLogRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.GridCellRecord", "GridCell")
                        .WithMany()
                        .HasForeignKey("GridCellId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SensorNodeRecord", "SensorNode")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Control.SimulationRunRecord", "SimulationRun")
                        .WithMany()
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");

                    b.Navigation("GridCell");

                    b.Navigation("SensorNode");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Users.UserRoleRecord", b =>
                {
                    b.HasOne("NatureProtector.Infrastructure.Postgres.Users.RoleRecord", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Users.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureProtector.Infrastructure.Postgres.Users.UserRecord", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.AreaRecord", b =>
                {
                    b.Navigation("Context");

                    b.Navigation("GridCells");

                    b.Navigation("Scenarios");

                    b.Navigation("SensorNodes");

                    b.Navigation("SimulationRuns");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ConfigurationVersionRecord", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("GridCells");

                    b.Navigation("RuleSetVersions");

                    b.Navigation("Scenarios");

                    b.Navigation("SensorNetworks");

                    b.Navigation("SensorNodes");

                    b.Navigation("SensorProfiles");

                    b.Navigation("SimulationRuns");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.DatasetArtifactRecord", b =>
                {
                    b.Navigation("ScenarioBindings");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.GridCellRecord", b =>
                {
                    b.Navigation("SensorNodes");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.ScenarioDefinitionRecord", b =>
                {
                    b.Navigation("DatasetBindings");

                    b.Navigation("DerivedScenarios");

                    b.Navigation("SimulationRuns");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorNetworkRecord", b =>
                {
                    b.Navigation("SensorNodes");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SensorProfileRecord", b =>
                {
                    b.Navigation("SensorNodes");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Control.SimulationRunRecord", b =>
                {
                    b.Navigation("RuntimeOperation");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Pipeline.InboxEventRecord", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Quarantines");

                    b.Navigation("Rejections");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Projection.AreaOperationalStateRecord", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("NatureProtector.Infrastructure.Postgres.Users.UserRecord", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
