apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: natureprotector-staging
namePrefix: ""
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      environment: staging
      phase: g8-1
      deployment-profile: qualification
commonAnnotations:
  natureprotector.io/claim-level: non-production-qualification
patches:
  - target:
      kind: Namespace
      name: natureprotector
    patch: |-
      - op: replace
        path: /metadata/name
        value: natureprotector-staging
  - target:
      kind: Deployment
      name: natureprotector-prevention
    patch: |-
      - op: add
        path: /spec/selector/matchLabels/environment
        value: staging
      - op: add
        path: /spec/selector/matchLabels/phase
        value: g8-1
      - op: add
        path: /spec/selector/matchLabels/deployment-profile
        value: qualification
      - op: add
        path: /spec/template/spec/topologySpreadConstraints/0/labelSelector/matchLabels/environment
        value: staging
      - op: add
        path: /spec/template/spec/topologySpreadConstraints/0/labelSelector/matchLabels/phase
        value: g8-1
      - op: add
        path: /spec/template/spec/topologySpreadConstraints/0/labelSelector/matchLabels/deployment-profile
        value: qualification
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 384Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
  - target:
      kind: ScaledObject
      name: natureprotector-prevention
    patch: |-
      - op: replace
        path: /spec/minReplicaCount
        value: 1
      - op: replace
        path: /spec/maxReplicaCount
        value: 2
      - op: replace
        path: /spec/fallback/replicas
        value: 1
  - target:
      kind: PodDisruptionBudget
      name: natureprotector-prevention
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0
  - target:
      kind: RabbitmqCluster
      name: natureprotector-rabbitmq
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/persistence/storageClassName
        value: standard-rwo
      - op: replace
        path: /spec/persistence/storage
        value: 10Gi
      - op: replace
        path: /spec/resources/requests/cpu
        value: 250m
      - op: replace
        path: /spec/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/resources/limits/cpu
        value: "1"
      - op: replace
        path: /spec/resources/limits/memory
        value: 512Mi
      - op: replace
        path: /spec/rabbitmq/additionalConfig
        value: |
          cluster_partition_handling = pause_minority
          queue_leader_locator = balanced
          default_queue_type = quorum
          quorum_queue.initial_cluster_size = 1
          disk_free_limit.absolute = 1GB
          vm_memory_high_watermark.relative = 0.6
          ssl_options.fail_if_no_peer_cert = false
          management.ssl.port = 15671
          consumer_timeout = 900000
  - target:
      kind: PodDisruptionBudget
      name: natureprotector-rabbitmq
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0
  - target:
      kind: Deployment
      name: natureprotector-otel
    patch: |-
      - op: add
        path: /spec/selector/matchLabels/environment
        value: staging
      - op: add
        path: /spec/selector/matchLabels/phase
        value: g8-1
      - op: add
        path: /spec/selector/matchLabels/deployment-profile
        value: qualification
      - op: add
        path: /spec/template/spec/topologySpreadConstraints/0/labelSelector/matchLabels/environment
        value: staging
      - op: add
        path: /spec/template/spec/topologySpreadConstraints/0/labelSelector/matchLabels/phase
        value: g8-1
      - op: add
        path: /spec/template/spec/topologySpreadConstraints/0/labelSelector/matchLabels/deployment-profile
        value: qualification
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
  - target:
      kind: PodDisruptionBudget
      name: natureprotector-otel
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0
  - target:
      kind: ResourceQuota
      name: natureprotector-runtime
    patch: |-
      - op: replace
        path: /spec/hard/requests.cpu
        value: "4"
      - op: replace
        path: /spec/hard/requests.memory
        value: 8Gi
      - op: replace
        path: /spec/hard/limits.cpu
        value: "8"
      - op: replace
        path: /spec/hard/limits.memory
        value: 16Gi
  - target:
      kind: SecretProviderClass
      name: natureprotector-runtime
    patch: |-
      - op: replace
        path: /spec/parameters/secrets
        value: |
          - resourceName: "projects/natureprotector-500518/secrets/np-staging-postgres-app-password/versions/1"
            path: "postgres-app-password"
          - resourceName: "projects/natureprotector-500518/secrets/np-staging-rabbitmq-app-username/versions/1"
            path: "rabbitmq-username"
          - resourceName: "projects/natureprotector-500518/secrets/np-staging-rabbitmq-app-password/versions/1"
            path: "rabbitmq-password"
  - target:
      kind: SecretProviderClass
      name: natureprotector-rabbitmq-tls
    patch: |-
      - op: replace
        path: /spec/parameters/secrets
        value: |
          - resourceName: "projects/natureprotector-500518/secrets/np-staging-rabbitmq-tls-certificate/versions/latest"
            path: "tls.crt"
          - resourceName: "projects/natureprotector-500518/secrets/np-staging-rabbitmq-tls-private-key/versions/latest"
            path: "tls.key"
          - resourceName: "projects/natureprotector-500518/secrets/np-staging-rabbitmq-ca-certificate/versions/latest"
            path: "ca.crt"
  - target:
      kind: SecretProviderClass
      name: natureprotector-cloud-sql-ca
    patch: |-
      - op: replace
        path: /spec/parameters/secrets
        value: |
          - resourceName: "projects/natureprotector-500518/secrets/np-staging-cloud-sql-server-ca/versions/1"
            path: "server-ca.pem"
