<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NatureProtector.Core\NatureProtector.Core.csproj" />
    <ProjectReference Include="..\NatureProtector.Infrastructure.Postgres\NatureProtector.Infrastructure.Postgres.csproj" />
    <ProjectReference Include="..\NatureProtector.Shared\NatureProtector.Shared.csproj" />
    <ProjectReference Include="..\NatureProtector.Shared.Observability\NatureProtector.Shared.Observability.csproj" />
  </ItemGroup>

</Project>
