@NatureProtector_Backoffice_Api_HostAddress = http://127.0.0.1:5254


// 1 -login / create user testing
POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/login
Content-Type: application/json

{
    "usernameOrEmail": "admin",
    "password": "admin123"
}

###

// copia o token e userId do login anterior para a linha abaixo e descomenta
 @adminToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFhYUBhYWEuYWFhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIkFkbWluIiwiUmVsZWFzZUFwcHJvdmVyIl0sIm5iZiI6MTc4NDYyOTE0OCwiZXhwIjoxNzg0NjMyNzQ4LCJpc3MiOiJOYXR1cmVQcm90ZWN0b3IiLCJhdWQiOiJOYXR1cmVQcm90ZWN0b3IuQmFja29mZmljZSJ9.p1hZp9O0nA1XW1ouEVcw210GpEq3Wv1u5xXiVae6DWY
// @adminId = 

POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/users
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "username": "simUser2",
    "password": "simUser123",
    "email": "newuse22r@example.com",
    "organization": "Nature Protector",
    "roles": ["Sim"]
}

###
POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/users
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "username": "pipeUser",
    "password": "pipeUser123",
    "email": "pipeuser@example.com",
    "organization": "Nature Protector",
    "roles": ["Pipeline"]
}

###
// Copia os userIds dos create User anteriores para as linhas abaixo e descomenta
// @simId = 
// @pipelineId =


// 2 - verificar roles dos users criados
// Valores: 1 - Admin, 2 - Sim, 3 - Pipeline

// Este deve retornar 200 OK
POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/users/{{simId}}/roles/2
Authorization: Bearer {{adminToken}}

###

// Este deve retornar 404 NOT FOUND
GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/users/{{simId}}/roles/2
Authorization: Bearer {{adminToken}}

###
// Este deve retornar 200 OK
GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/users/{{adminId}}/roles/1
Authorization: Bearer {{adminToken}}

### 
// Este deve retornar 404 NOT FOUND
GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/users/{{adminId}}/roles/2
Authorization: Bearer {{adminToken}}

###
// Este deve retornar 200 OK
GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/users/{{pipelineId}}/roles/3
Authorization: Bearer {{adminToken}}


// 3 - Login com os users criados para obter token de acesso e testar endpoints com diferentes roles
###
POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/login
Content-Type: application/json

{
    "usernameOrEmail": "pipeUser",
    "password": "pipeUser123"
}

###

POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/login
Content-Type: application/json

{
    "usernameOrEmail": "simUser2",
    "password": "simUser123"
}

// Copia os tokens do login anteriores para as linhas abaixo e descomenta
// @simToken =
// @pipeToken = 
###

// Deve retornar 200 OK, desde que se tenha autorização, pode-se obter informação de control/areas/{areaCode}/scenarios
GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/areas/proenca-a-nova/scenarios
Accept: application/json
Authorization: Bearer {{adminToken}}

###
// Mesmo caso, o role Sim deve consegui pedir o GET
GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/areas/proenca-a-nova/scenarios
Accept: application/json
Authorization: Bearer {{simToken}}

###
// Outra vez, mesmo resultado para o role Pipeline
GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/areas/proenca-a-nova/scenarios
Accept: application/json
Authorization: Bearer {{pipeToken}}



###

// control/runtime/runs só permite roles Sim e Admin
// Este deve retornar 200 OK
POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/runtime/runs
Accept: application/json
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "AreaCode": "proenca-a-nova",
    "ScenarioCode": "scenario_a"
}

###
// Este deve retornar 200 OK
POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/runtime/runs
Accept: application/json
Authorization: Bearer {{simToken}}

Content-Type: application/json

{
    "AreaCode": "proenca-a-nova",
    "ScenarioCode": "scenario_a"
}
###
// Este deve retornar 403 FORBIDDEN, pois o role Pipeline não tem acesso a este endpoint
POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/runtime/runs
Accept: application/json
Authorization: Bearer {{pipeToken}}
Content-Type: application/json

{
    "AreaCode": "proenca-a-nova",
    "ScenarioCode": "scenario_a"
}

###
// 4 - adicionar Sim ao user Pipeline e testar se tem acesso ao endpoint control/runtime/runs

PUT {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/users/{{pipelineId}}/roles/2
Authorization: Bearer {{adminToken}}

// Como o token ainda mantém apenas o role Pipeline, este deve retornar 403 FORBIDDEN
###
POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/runtime/runs
Accept: application/json
Authorization: Bearer {{pipeToken}}
Content-Type: application/json

{
    "AreaCode": "proenca-a-nova",
    "ScenarioCode": "scenario_a"
}

###
POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/users-roles/login
Content-Type: application/json

{
    "usernameOrEmail": "pipeUser",
    "password": "pipeUser123"
}

// @pipeToken2 = 
###
// Agora, com o role Sim adicionado, este deve retornar 200 OK
POST {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/runtime/runs
Accept: application/json
Authorization: Bearer {{pipeToken2}}
Content-Type: application/json

{
    "AreaCode": "proenca-a-nova",
    "ScenarioCode": "scenario_a"
}

// ----------------------------------------------------------------------------------------
// testes de rotas de controlo antigo

###

GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/configurations/active
Accept: application/json
Authorization: Bearer {{adminToken}}

###

GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/areas
Accept: application/json
Authorization: Bearer {{adminToken}}

###

GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/areas/proenca-a-nova/cells/operational-state
Accept: application/json
Authorization: Bearer {{adminToken}}

###

GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/areas/proenca-a-nova/alerts/active
Accept: application/json
Authorization: Bearer {{adminToken}}

###

GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/simulation-runs?areaCode=proenca-a-nova
Accept: application/json
Authorization: Bearer {{adminToken}}

###

GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/areas/proenca-a-nova/GeoJSON
Accept: application/json
Authorization: Bearer {{adminToken}}

###

GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/areas/proenca-a-nova/grid-cells
Accept: application/json
Authorization: Bearer {{adminToken}}


###
GET {{NatureProtector_Backoffice_Api_HostAddress}}/api/control/runtime/getTables
Accept: application/json
Authorization: Bearer {{adminToken}}