import type { RuntimeSummaryResponse } from './types';

export function createUiRuntimeSummaryFixture(
  overrides: Partial<RuntimeSummaryResponse> = {},
): RuntimeSummaryResponse {
  return {
    generatedAtUtc: '2026-06-13T22:00:00Z',
    recentWindowMinutes: 30,
    areaCode: 'proenca-a-nova',
    currentRun: null,
    latestRun: {
      id: 'run-001',
      areaCode: 'proenca-a-nova',
      scenarioCode: 'scenario_b',
      scenarioName: 'Scenario B - High Risk',
      status: 'Completed',
      configurationVersionNumber: 1,
      createdAt: '2026-06-13T21:00:00Z',
      startedAt: '2026-06-13T21:01:00Z',
      endedAt: '2026-06-13T21:14:00Z',
      durationSeconds: 780,
      logicalStartTimestamp: '2020-09-13T11:00:00Z',
      intervalSeconds: 300,
      numberOfCycles: 36,
      executionSeed: 42,
      metadataJson: null,
      metadataJsonStatus: 'valid',
      orchestratorCorrelationId: null,
      runOverrides: null,
    },
    pipeline: {
      inboxTotal: 36,
      inboxRecent: 36,
      inboxByStatus: [],
      attemptsRecent: 36,
      attemptsByOutcomeAndError: [],
      rejectedRecent: 0,
      rejectedTotal: 0,
      rejectedByCode: [],
      quarantinedRecent: 0,
      quarantinedTotal: 0,
      quarantinedByCode: [],
      latestRejected: [],
      latestQuarantined: [],
      latestFailedAttempts: [],
    },
    risk: {
      recentCount: 36,
      minScore: 0.42,
      maxScore: 0.91,
      latestTimestamp: '2026-06-13T21:14:00Z',
      recentScores: [],
    },
    areaOperationalState: {
      areaCode: 'proenca-a-nova',
      configurationVersionNumber: 1,
      snapshotTimestamp: '2026-06-13T21:15:00Z',
      aggregateRiskScore: 0.78,
      aggregateRiskLevel: 'VeryHigh',
      severity: 'Critical',
      summary: 'Persisted projection from the prototype runtime.',
      assessmentCount: 36,
      updatedAt: '2026-06-13T21:16:00Z',
      alertState: 'Alarm',
      coverageStatus: 'Complete',
      freshnessStatus: 'Fresh',
      carryForwardStatus: 'None',
      lastAssessmentTimestamp: '2026-06-13T21:14:00Z',
      lastProjectionUpdatedAt: '2026-06-13T21:16:00Z',
      operationalStatusReason: null,
    },
    cellOperationalStateCount: 12,
    activeAlerts: [],
    freshness: {
      freshCount: 12,
      staleCount: 0,
      expiredCount: 0,
      oldestIncludedAssessment: '2026-06-13T21:00:00Z',
      latestIncludedAssessment: '2026-06-13T21:14:00Z',
      freshSeconds: 120,
      staleSeconds: 300,
      note: 'Prototype freshness window.',
    },
    scoreComponents: {
      npScore: 0.78,
      baseRisk: 0.72,
      adjustedScore: 0.78,
      score100: 78,
      meteorologyComponent: 0.8,
      droughtComponent: 0.7,
      territoryComponent: 0.6,
      hazardComponent: 0.6,
      fuelComponent: 0.7,
      geomorphologyComponent: 0.6,
      confidenceFactor: 1,
      integrityFactor: 1,
      dominantDriver: 'Meteorology',
      parameterSetVersion: 'Candidate Parameter Set V1.0',
      calculationStatus: 'Complete',
      limitations: null,
      latestAssessmentTimestamp: '2026-06-13T21:14:00Z',
      npRiskClass: 'VeryHigh',
      npRiskClassLabel: 'Very high',
    },
    indexComparison: {
      fireWeatherIndex: 17.07,
      normalizedFireWeatherIndex: 0.213,
      fireWeatherCalculationStatus: 'CompleteWithCandidateDefaults',
      keetchByramDroughtIndex: 16.56,
      normalizedKeetchByramDroughtIndex: 0.0207,
      kbdiCalculationStatus: 'LimitedAntecedentHistory',
      provenance: 'candidate_calculated',
      limitations: 'Limited antecedent history',
      dailyPrecipitationMillimeters: 0,
      logicalDate: '2020-09-13',
      calculatedFireWeatherIndex: 17.07,
      referenceFireWeatherIndex: null,
      fireWeatherIndexValueSource: 'calculated_candidate',
      fireWeatherIpmaClass: 'Moderate',
      fireWeatherIpmaClassLabel: 'Moderado',
      fireWeatherEffisClass: 'Moderate',
      fireWeatherThresholdDistanceToNextClass: 0.13,
      fireWeatherNextIpmaClass: 'High',
      calculatedKeetchByramDroughtIndex: 16.56,
      referenceKeetchByramDroughtIndex: null,
      kbdiValueSource: 'calculated_candidate',
      kbdiDrynessClass: 'VeryLowDryness',
      kbdiDrynessClassLabel: 'Secura muito baixa',
      kbdiAntecedentHistoryQuality: 'LimitedAntecedentHistory',
      kbdiAntecedentDays: 0,
      portugueseContextRiskProxyClass: 'High',
      portugueseContextRiskProxyLabel: 'Elevado',
      territorialHazardProxyClass: 'High',
      localFwiPercentileStatus: 'NotAvailable',
      localFwiPercentile: null,
      localFwiPercentileReason: 'historical_local_fwi_distribution_not_materialized',
    },
    limitations: [],
    warnings: [],
    ...overrides,
  };
}


