using NatureProtector.Core.Primitives;

/*
 * This class represents an operator-facing preventive alert generated by the domain.
 *
 * Rationale:
 * - Alerts communicate relevant preventive conditions in a compact and actionable form.
 * - In the current target model, Alert is intentionally lightweight and focused on
 *   communication semantics rather than operational dispatch or detection workflows.
 *
 * Design considerations:
 * - The identity, severity, message and creation time are required at construction.
 * - Acknowledgement is the only mutable behaviour because it reflects an operator action
 *   performed after the alert has been issued.
 * - The class is deliberately decoupled from FireEvent, AlertType and destination logic,
 *   because those belong to the older operational model rather than the current target model.
 */

namespace NatureProtector.Core.Communication;

public sealed class Alert
{
    /// <summary>
    /// Globally unique identifier of the alert.
    /// </summary>
    public Guid Id { get; }

    /// <summary>
    /// Communication severity associated with the alert.
    /// </summary>
    public Severity Severity { get; private set; }

    /// <summary>
    /// Human-readable alert message intended for operators or downstream consumers.
    /// </summary>
    public string Message { get; private set; }

    /// <summary>
    /// Instant when the alert was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; }

    /// <summary>
    /// Indicates whether the alert has already been acknowledged.
    /// </summary>
    public bool IsAcknowledged { get; private set; }

    /// <summary>
    /// Creates a new Alert instance.
    /// </summary>
    /// <param name="id">
    /// Globally unique identifier of the alert.
    /// </param>
    /// <param name="severity">
    /// Communication severity of the alert.
    /// </param>
    /// <param name="message">
    /// Human-readable alert message.
    /// </param>
    /// <param name="createdAt">
    /// Timestamp of alert creation.
    /// </param>
    public Alert(
        Guid id,
        Severity severity,
        string message,
        DateTimeOffset createdAt)
    {
        if (id == Guid.Empty)
        {
            throw new ArgumentException(
                "Alert identifier must not be an empty GUID.",
                nameof(id));
        }

        if (string.IsNullOrWhiteSpace(message))
        {
            throw new ArgumentException(
                "Alert message must not be null or whitespace.",
                nameof(message));
        }

        if (createdAt == default)
        {
            throw new ArgumentException(
                "Alert creation time must be a valid, non-default value.",
                nameof(createdAt));
        }

        Id = id;
        Severity = severity;
        Message = message.Trim();
        CreatedAt = createdAt;
        IsAcknowledged = false;
    }

    /// <summary>
    /// Marks the alert as acknowledged.
    /// </summary>
    /// <remarks>
    /// The operation is intentionally idempotent. Calling it more than once
    /// leaves the alert in the same acknowledged state.
    /// </remarks>
    public void Acknowledge()
    {
        // Idempotent acknowledgement avoids unnecessary failures in simple flows.
        if (IsAcknowledged)
        {
            return;
        }

        IsAcknowledged = true;
    }
}