/*
 * This class represents a preventive recommendation generated by the domain.
 *
 * Rationale:
 * - Recommendations complement alerts by describing suggested preventive actions
 *   or follow-up guidance in a structured way.
 * - They are kept distinct from Alert because a recommendation is not necessarily
 *   urgent, even when it is operationally relevant.
 *
 * Design considerations:
 * - The class is immutable after construction because recommendations should be
 *   treated as issued guidance rather than mutable workflow state.
 * - Priority is represented as an integer to keep ordering simple for the current phase.
 * - The model intentionally remains lightweight and does not yet encode ownership,
 *   status transitions or execution tracking.
 */

namespace NatureProtector.Core.Communication;

public sealed class Recommendation
{
    /// <summary>
    /// Globally unique identifier of the recommendation.
    /// </summary>
    public Guid Id { get; }

    /// <summary>
    /// Human-readable recommendation message.
    /// </summary>
    public string Message { get; }

    /// <summary>
    /// Relative priority of the recommendation.
    /// Higher values indicate greater urgency or importance.
    /// </summary>
    public int Priority { get; }

    /// <summary>
    /// Instant when the recommendation was created.
    /// </summary>
    public DateTimeOffset CreatedAt { get; }

    /// <summary>
    /// Creates a new Recommendation instance.
    /// </summary>
    /// <param name="id">
    /// Globally unique identifier of the recommendation.
    /// </param>
    /// <param name="message">
    /// Human-readable recommendation message.
    /// </param>
    /// <param name="priority">
    /// Relative priority of the recommendation.
    /// </param>
    /// <param name="createdAt">
    /// Timestamp of recommendation creation.
    /// </param>
    public Recommendation(
        Guid id,
        string message,
        int priority,
        DateTimeOffset createdAt)
    {
        if (id == Guid.Empty)
        {
            throw new ArgumentException(
                "Recommendation identifier must not be an empty GUID.",
                nameof(id));
        }

        if (string.IsNullOrWhiteSpace(message))
        {
            throw new ArgumentException(
                "Recommendation message must not be null or whitespace.",
                nameof(message));
        }

        if (priority < 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(priority),
                priority,
                "Priority must be greater than or equal to zero.");
        }

        if (createdAt == default)
        {
            throw new ArgumentException(
                "Recommendation creation time must be a valid, non-default value.",
                nameof(createdAt));
        }

        Id = id;
        Message = message.Trim();
        Priority = priority;
        CreatedAt = createdAt;
    }
}