$ErrorActionPreference = 'Stop'
$env:RabbitMq__Password = 'np_dev_pass'
$env:RabbitMq__HostName = 'localhost'
$env:InfluxDb__Url = 'http://localhost:8181'
$env:POSTGRES_PORT = '5433'
$env:POSTGRES_DB = 'natureprotector'
$env:ASPNETCORE_ENVIRONMENT = 'Development'
$env:POSTGRES_USER = 'np'
$env:POSTGRES_PASSWORD = 'np_dev_pass'
$env:VITE_API_PROXY_TARGET = 'http://127.0.0.1:5254'
$env:RabbitMq__Port = '5672'
$env:RabbitMq__UserName = 'np'
$env:POSTGRES_HOST = 'localhost'
$env:DOTNET_ENVIRONMENT = 'Development'
$env:ASPNETCORE_URLS = 'http://127.0.0.1:5254'
npm run dev -- --host 127.0.0.1 --port 5173 --strictPort
