apiVersion: 1

datasources:
  - name: NatureProtectorInfinityJson
    uid: natureprotector-infinity-json
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: ${INFLUXDB_URL}
    editable: true
    jsonData:
      auth_method: bearerToken
      allowedHosts:
        - ${INFLUXDB_URL}
      timeoutInSeconds: 60
      httpHeaderName1: Accept
    secureJsonData:
      bearerToken: ${INFLUXDB_TOKEN}
      httpHeaderValue1: application/json
