apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: natureprotector-postgres
    type: postgres
    url: localhost:${POSTGRES_PORT}
    editable: true
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      version: "16"
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false