apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: natureprotector-staging
labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      environment: staging
      phase: g8-1
      deployment-profile: qualification
commonAnnotations:
  natureprotector.io/claim-level: non-production-qualification
