apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: natureprotector-production
namePrefix: ""
commonLabels:
  environment: production
  phase: g8-1
patches:
  - target:
      kind: Namespace
      name: natureprotector
    patch: |-
      - op: replace
        path: /metadata/name
        value: natureprotector-production
  - target:
      kind: ScaledObject
      name: natureprotector-prevention
    patch: |-
      - op: replace
        path: /spec/minReplicaCount
        value: 3
      - op: replace
        path: /spec/maxReplicaCount
        value: 18
