This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./Report.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Report.acn....done (9 entries accepted, 0 rejected).
Sorting entries....done (29 comparisons).
Generating output file Report.acr....done (12 lines written, 0 warnings).
Output written in Report.acr.
Transcript written in Report.alg.
