#!/usr/bin/env python3
"""Derive a KEDA queue target from measured one-replica capacity."""
from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
from pathlib import Path
from typing import Any


def read_rows(path: Path) -> list[dict[str, Any]]:
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    for row in rows:
        row["publisher_rate"] = float(row["publisher_rate"])
        row["replicas"] = int(row["replicas"])
        row["processed_rate"] = float(row["processed_rate"])
        row["p95_ms"] = float(row["p95_ms"])
        row["backlog_end"] = int(row["backlog_end"])
        row["correctness_pass"] = row["correctness_pass"].lower() == "true"
    return rows


def recommendation(rows: list[dict[str, Any]], acceptable_delay: float, min_replicas: int, max_replicas: int) -> dict[str, Any]:
    baseline = [row for row in rows if row["experiment"] == "S1" and row["replicas"] == 1 and row["correctness_pass"]]
    if not baseline:
        raise ValueError("At least one correct S1 one-replica baseline row is required.")
    rates = [row["processed_rate"] for row in baseline]
    per_replica_rate = statistics.median(rates)
    queue_target = max(1, math.floor(per_replica_rate * acceptable_delay))
    activation = max(1, math.floor(queue_target * 0.1))
    correctness = all(row["correctness_pass"] for row in rows)
    return {
        "schemaVersion": 1,
        "baselineSamples": len(baseline),
        "processingRatePerReplicaMedian": per_replica_rate,
        "acceptableQueueDelaySeconds": acceptable_delay,
        "targetBacklogPerReplica": queue_target,
        "activationBacklog": activation,
        "minReplicaCount": min_replicas,
        "maxReplicaCount": max_replicas,
        "allExperimentRowsCorrect": correctness,
        "readyForScalingExperiment": correctness and {row["experiment"] for row in rows} == {f"S{number}" for number in range(1, 9)},
    }


def render_yaml(value: dict[str, Any]) -> str:
    query = "SELECT CASE WHEN ((SELECT COUNT(*) FROM pipeline.event_inbox WHERE status IN (0,1,5)) + (SELECT COUNT(*) FROM projection.cycle_settlement WHERE finalized_at IS NULL)) > 0 THEN 2 ELSE 0 END;"
    return f"""# Generated by scripts/autoscaling/analyze-capacity.py from measured capacity.\napiVersion: keda.sh/v1alpha1\nkind: ScaledObject\nmetadata:\n  name: natureprotector-prevention-experiment\nspec:\n  scaleTargetRef:\n    name: natureprotector-prevention\n    envSourceContainerName: prevention\n  pollingInterval: 15\n  cooldownPeriod: 300\n  minReplicaCount: {value['minReplicaCount']}\n  maxReplicaCount: {value['maxReplicaCount']}\n  fallback:\n    failureThreshold: 3\n    replicas: {value['minReplicaCount']}\n  advanced:\n    horizontalPodAutoscalerConfig:\n      behavior:\n        scaleUp:\n          stabilizationWindowSeconds: 15\n          policies:\n            - type: Percent\n              value: 100\n              periodSeconds: 60\n            - type: Pods\n              value: 2\n              periodSeconds: 60\n        scaleDown:\n          stabilizationWindowSeconds: 300\n          policies:\n            - type: Percent\n              value: 25\n              periodSeconds: 120\n  triggers:\n    - type: rabbitmq\n      name: ingestion-queue-depth\n      metricType: AverageValue\n      metadata:\n        protocol: amqp\n        queueName: np.ingestion.readings\n        mode: QueueLength\n        value: \"{value['targetBacklogPerReplica']}\"\n        activationValue: \"{value['activationBacklog']}\"\n      authenticationRef:\n        name: natureprotector-rabbitmq\n    - type: postgresql\n      name: retry-settlement-guardrail\n      metricType: Value\n      metadata:\n        host: missing-cloud-sql-private-ip\n        port: \"5432\"\n        userName: np_app\n        passwordFromEnv: POSTGRES_PASSWORD\n        dbName: natureprotector\n        sslmode: require\n        query: \"{query}\"\n        targetQueryValue: \"1\"\n        activationTargetQueryValue: \"0\"\n"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("--config", type=Path, default=Path("config/autoscaling/capacity-experiments.json"))
    parser.add_argument("--output-dir", type=Path, default=Path("artifacts/autoscaling/capacity"))
    args = parser.parse_args()
    config = json.loads(args.config.read_text(encoding="utf-8"))
    rows = read_rows(args.input)
    result = recommendation(rows, float(config["acceptableQueueDelaySeconds"]), int(config["minReplicaCount"]), int(config["maxReplicaCount"]))
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "autoscaling-recommendation.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    (args.output_dir / "prevention-scaling.generated.yaml").write_text(render_yaml(result), encoding="utf-8")
    print(json.dumps(result, indent=2))
    return 0 if result["readyForScalingExperiment"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
